### ISSUE TITLE
Syntax Highlighting Stops Working After First Session After Install

### ISSUE THREAD

**Issue by daviddl** [arthwang/vsc-prolog#1]
VSC-Prolog Version: 0.4.7

No other steps were done prior to this to configure the extension. 

1. Install the VSC-Prolog Extension
2. Open a Prolog source file
3. Notice that the syntax highlighting works as intended. 
4. Close VSC
5. Relaunch VSC
6. You should see the previously opened Prolog source file; notice that the syntax highlighting no longer works. 

Uninstalling the extension, reloading VSC and reinstalling the extension will restore the syntax highlighting. 

I have repeated this 3/3 times. 
OS: Windows 10

**Comment by arthwang** [comment]
Thank you for your information, but I'm sorry that VSC-Prolog is developed and tested in Debian operating system, not tested under other environments.

This is noticed in the first paragraph of the README.md:

Note before installation

This extension can be installed via extensions viewlet of VS Code or 'Extensions: install extension' command from the command palette. The author notices that it is developed and tested in SWI-Prolog 7.4.2, ECLiPSe 6.1 and VS Code 1.15on Debian 9.0 (stretch). It's not yet tested under other environments.

Please update to 7.5.13 of swipl if you want to use 'Show all references' feature.

I'm not sure when I would have time to port the extension to Windows os. Sorry for that again.

Arthur Wang

**Comment by arthwang** [comment]
I have made this extension cross-plateform and tested on Windows 10. Have a try please.

**Comment by daviddl** [comment]
Alright, I'll give it a shot by tomorrow. Thank you.

**Comment by daviddl** [comment]
Seems like syntax highlighting now works all the time. Thank you for fixing
it.
