### ISSUE TITLE
Configuration help for Windows 10?

### ISSUE THREAD

**Issue by MyriaCore** [arthwang/vsc-prolog#11]
Sorry in advance if this is a stupid question, but I've been having some trouble with getting gtrace to work when I use the 'load in prolog' command.

Right now I'm using swipl.exe as the prolog executable, but I can't seem to use things like gtrace (which I rely on because I'm still learning prolog, and it helps me visualize things), almost as if its module wasn't loaded. I tried to get it by using `:- use_module(library(gui_tracer)).`, but it would throw an error saying `source_sink 'library(pce)' does not exist`. 

Am I using use_module incorrectly? Am I supposed to be using swipl-win.exe instead? If so, what launch args should I use?

**Comment by arthwang** [comment]
It looks unlike the issue of VSC-Prolog or VSCode.  Just try guitracer/0 in swipl REPL outside VSCode to confirm. 
BTW VSC-Prolog provide basic gui-like debugger, why not have a try? Refer to README.mk of the VSC-Prolog for that.

**Comment by arthwang** [comment]
Sorry for late response.  Try to remove spaces in the directory names to handle the path issue.

**Comment by MyriaCore** [comment]
Yeah, I'm gonna close this because I'm pretty sure there are just binaries sitting around that I don't know swipl-win is loading. I figured out a workaround by just hardcoding a debug option to load a prolog file.

Sorry to bother you!
