### ISSUE TITLE
Syntax Highlighting for `=..` operator is broken

### ISSUE THREAD

**Issue by MyriaCore** [arthwang/vsc-prolog#14]
![ybphfit 1](https://user-images.githubusercontent.com/35076430/40283709-a10062e2-5c50-11e8-89bd-424fb9ed884b.png)
The period immediately after the = is mistakenly highlighted in 'end of predicate' purple.
Dialect is SWI-Prolog, Platform is Windows 10.

**Comment by arthwang** [comment]
Please refer to my explanation for syntax highlighting of Prolog in #9.

**Comment by MyriaCore** [comment]
Yeah, I've dug around in the src files and figured that out. Is there any way we could sculpt a better solution? Maybe we could use a grammar / AST kinda setup for syntax highlighting? That'd require tons and tons of reconfig, but I feel like it'd be worth it to have better control over the highlighting.

**Comment by arthwang** [comment]
It sounds interesting but I don't have time to dive into that. PR is much appreciated if you try it.

**Comment by MyriaCore** [comment]
Yeah, I'll see what I can do, but I'm still learning Prolog, so I'll probably be tinkering with it for a few eons. Should I close this issue until I come up with something, or should I just keep it open?

**Comment by arthwang** [comment]
Okey, thank you very much!

**Comment by MyriaCore** [comment]
Upon further thought, ASTs would be sorta stupid cause would have to walk up and down the tree again and again, so I'll just try to learn regex so I can change the grammar to be better.
