### ISSUE TITLE
Cannot execute command 'Prolog: load document' on Windows 10

### ISSUE THREAD

**Issue by ericmatte** [arthwang/vsc-prolog#20]
Hi,

I am unable to run my .pl file into the terminal using the command 'Prolog: load document'.
I have setup my "prolog.executablePath" to "C:/Program Files (x86)/swipl/bin/swipl", which seems to be working (no linter error).

When I try to run the command (alt+X, L), nothing happens.

Thank you!

**Comment by ericmatte** [comment]
Closed due to inactivity.

**Comment by arthwang** [comment]
Sorry for late response.  Try to add '.exe' to swipl executable, i.e.  "c:/Program files (x86)/swipl/bin/swipl.exe".

**Comment by ericmatte** [comment]
Great, that was the culprit. Adding the ".exe" at the end did the trick. Thank you!
