### ISSUE TITLE
Cannot debug the prolog file, prolog executable not found

### ISSUE THREAD

**Issue by AlessioAtroni** [arthwang/vsc-prolog#25]
When trying to debug my prolog files, i get this error:
`Cannot debug the prolog file. The Prolog executable '/usr/local/Cellar/swi-prolog/7.7.19/bin/swipl' was not found. Correct 'runtimeExecutable' setting in launch.json file.`

However bash command:
`[ -f /usr/local/Cellar/swi-prolog/7.7.19/bin/swipl ] && echo "Found" || echo "Not found"`
Prints:
`Found`

**Comment by arthwang** [comment]
Looks weird.  What does 'which' command print?  swipl starts normally in terminal?

**Comment by AlessioAtroni** [comment]
`which swipl`
Prints:
`/usr/local/bin/swipl`

Using that path as `runtimeExecutable` produces the error below:
`Cannot debug the prolog file. The Prolog executable '/usr/local/bin/swipl' was not found. Correct 'runtimeExecutable' setting in launch.json file.`

**Comment by arthwang** [comment]
Can you start swipl in terminal or Interminal of vscode?

**Comment by AlessioAtroni** [comment]
I can start swipl in both terminals, the only feature not working is the debugger.

**Comment by arthwang** [comment]
Can you load .pl into swipl process in Interminal via vsc-prolog (from command or context menu)?
As for reference, would you please post your launch.json ?

**Comment by AlessioAtroni** [comment]
## launch.json (Not working)
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Prolog Debugger",
            "type": "prolog",
            "request": "launch",
            "runtimeExecutable": "/usr/local/bin/swipl",
            "runtimeArgs": [],
            "env": {},
            "program": "\"${file}\"",
            "cwd": "\"${fileDirname}\"",
            "startupQuery": "start",
            "stopOnEntry": true,
            "traceCmds": {
                "continue": [
                    "leap",
                    "l"
                ],
                "stepover": [
                    "skip",
                    "s"
                ],
                "stepinto": [
                    "creep",
                    "c"
                ],
                "stepout": [
                    "up",
                    "u"
                ]
            }
        }
    ]
}
```

## tasks.json (Working build shortcut)
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "run",
            "type": "shell",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "command": "clear && swipl -sq \"${file}\""
        }
    ]
}
```

**Comment by arthwang** [comment]
I reproduced the issue using your launch.json and the error disappear if I remove the escaped double quotes in "program": "\"${file}\"",  "cwd": "\"${fileDirname}\"".    That is,  correct them to: "program": "${file}", "cwd":"${fileDirname}".
Hope this solve the issue.

**Comment by AlessioAtroni** [comment]
Thanks a lot, this solved the issue I'm going to open two other issues for the remaining problems.
