### ISSUE TITLE
Executable path for linter

### ISSUE THREAD

**Issue by LeshnaShamloll** [arthwang/vsc-prolog#4]
Hello

I am unsure of where to put the "prolog.executablePath": "..." setting. Any help would be welcomed.

**Comment by arthwang** [comment]
1)Go to VS Code's menu: File/Preferences/Settings, you will see User Settings interface. 
2)Input prolog in the search area
3)mouse over on "prolog.executablePath" will show up a pen icon
4)mouse over the icon, you see 'Edit' tip
5)click the icon and then 'Copy to Settings' menu
6)edit the path on the right editor to where your 'swipl' locates, e.g. C:/Program files/swipl/bin/swipl in Windows.

**Comment by LeshnaShamloll** [comment]
Thank you very much :)


________________________________

**Comment by marcoswmv** [comment]
I get the following output every time a change anything in the pl file 

"Cannot lint the prolog file. The Prolog executable was not found. Use the 'prolog.executablePath' setting to configure" 

I am using vs code on MacOS Mojave

**Comment by asemic-horizon** [comment]
I was having the same problems as Leshna even after arthwang's configuration steps.

This is what both my user and workplace `settings.json` looked like after changing settings in the VSCode GUI:

```
{
    "terminal.external.windowsExec": "C:\\WINDOWS\\System32\\wsl.exe",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
    "prolog.executablePath": "\"C:\\Program Files\\swipl\\bin\\swipl.exe\\",
}
```

Note the rogue ``\ `` at the beginning of that string. I don't know why that happens, but others may encounter this problem too. Remove that so it looks like

```
    "prolog.executablePath": "C:\\Program Files\\swipl\\bin\\swipl.exe\\",
```

and you should be good to go; worked for me.

**Comment by Anurag-Nagpal** [comment]
Hi I compiled my program using
`swipl <filename>.pl`

but how do I exit the terminal ?
![image](https://user-images.githubusercontent.com/73398296/135155965-f86f37dc-a9fd-4085-9501-22e86eaecd4f.png)

**Comment by echoix** [comment]
When you are shown these actions, you can try pressing `h` to see the options available, but one of these is `e`, for exit. 

To get to this, you do `CTRL`+`C`,so it is `CTRL`+`C` then `e`. 

I hadn't have the time to try, but maybe `CTRL`+`D` halts in one keystroke, you could tell me if it's the same effect.

**Comment by Stukeyy** [comment]
I installed swi-prolog via Homebrew on MacOS, to find the executable path I ran **which swi-prolog** in the terminal and that gave me the path **/usr/local/bin/swipl** which I then pasted in the VSC-prolog executable path setting and then the file was linted

**Comment by geeth24** [comment]
Installing **swi-prolog** via homebrew put mine in `/opt/homebrew/bin/swipl`.
