### ISSUE TITLE
use_module doesn't work correctly

### ISSUE THREAD

**Issue by joeystz** [arthwang/vsc-prolog#40]
Hi,
i swapped from SWI-Prolog to your VSC-Extension and opened the same folder, i've already worked with.
But my whole code is marked with errors, because the use_module command doesn't find the files, which are obviously existing.
Executing the files on the command line with swipl does work correctly, just debugging and code-completion is not working at all now..
Can you help me out?
I already tried " instead of ' and swapping to backslashes.
Thanks.
Kind regards
Joey

**Comment by joeystz** [comment]
![vsc-use-module-error](https://user-images.githubusercontent.com/52487370/62462058-b44da980-b786-11e9-8168-fc9f1f80ca29.jpg)
![vsc32424](https://user-images.githubusercontent.com/52487370/62462154-eeb74680-b786-11e9-9e02-3b264486697f.jpg)

forgot the images.

**Comment by arthwang** [comment]
Hi,
VSCode references path relative to the project root. So just write your
code like use_module(‘src/clpstr’).
Hope this helps you.
With best regards,
Arthur Wang

joeystz <notifications@github.com> 于2019年8月5日周一 下午7:41写道：

**Comment by joeystz** [comment]
Hi, that worked for me.
Thanks a lot!
