### ISSUE TITLE
Unable to get linter to "see" prolog executable

### ISSUE THREAD

**Issue by ddejohn** [arthwang/vsc-prolog#46]
Windows 10 NT

`swipl` is on my PATH, I can run it just fine, but VSC-prolog can't find the executable when I point it to the install location "C:/Program Files/swipl/bin/".

I've tried `"prolog.executablePath": "C:\\Program Files\\swipl\\bin\\",`

As well as with forward slashes, using the settings UI and manually editing the JSON settings file, nothing works. If I explicitly point it to `"prolog.executablePath": "C:\\Program Files\\swipl\\bin\\swipl-win.exe"`, the linter will open it on typing, which is obviously useless, but at least proves that my path isn't incorrect.

**Comment by arthwang** [comment]
It needs to include the executable file name: “C:/Program
Files/swipl/bin/swipl.exe”.

Devon DeJohn <notifications@github.com> 于2020年3月31日周二 上午5:18写道：
