### ISSUE TITLE
unable to recognize predicates from other source files

### ISSUE THREAD

**Issue by jtmr05** [arthwang/vsc-prolog#56]
When consulting other source files, the predicates declared there are not recognized. They are instead marked as undefined.

`something.pl`

![image](https://user-images.githubusercontent.com/62111562/142942335-0f6eca39-454f-4016-868f-c1d808eeab67.png)

`otherthing.pl`

![image](https://user-images.githubusercontent.com/62111562/142942475-2c6f0d67-4b99-4e99-9368-3bd482e9f0ec.png)

As you can see, they are in the same directory. I hope I'm not doing anything wrong since I'm fairly new to Prolog. Cheers.

**Comment by minimaximal** [comment]
I'm personally not sure and also new to prolog (student 1st term), but I think this can't be working because for importing a header / library into a other you typically use "include".

e. g.
:- include('./1_concatenate.pl').

**Comment by jtmr05** [comment]
That does solve the problem apparently. I still find it a bit that consult doesn't work, when it's essentially the same thing.

**Comment by minimaximal** [comment]
Now it really confuses me, I could swear that 2 weeks ago when I tried to include a predicate from another file, "consult" didn't work at all, but when I try to recreate your problem or my observation, "include" and "consult" work just fine, no errors, neither from swi-pl cli nor in the syntax check of vsc-prolog. 
I hope I could help you for now, but this behavior quiete misterious.

**Comment by jtmr05** [comment]
Same thing actually. I have no idea what's happening.

**Comment by manel27** [comment]
I don't know how to fix the consult/1 problem, but I use compile/1 whenever a file shares declarations with another

**Comment by zelezny** [comment]
I am experiencing "predicate undefined" messages for predicates imported using the swi module mechanism, i.e. through the :- use_module(...) call.

**Comment by jtmr05** [comment]
this project is very much dead, so might as well close this

**Comment by zelezny** [comment]
Hi Arthur,

I was just wondering whether you've abandoned the project simply because
you do not have time/interest for it or because there is now another method
to do Prolog in VSC that supersedes your extension.

Anyway, thanks for the extension, it really makes Prolog more comfortable.

Best wishes
Filip
