### ISSUE TITLE
Debugger Error

### ISSUE THREAD

**Issue by adericotur** [arthwang/vsc-prolog#8]
When I try to enter debug mode, It throws errors regarding the paths: 

```
ERROR: Syntax error: Illegal \u or \U sequence
ERROR: prolog_debugger:set_breakpoints('C:
ERROR: ** here **
ERROR: \Users\Andrei\Desktop\Probleme Sicstus Prolog\Laborator1\test.pl', "") . 
```

I think it doesn't parse the path correctly and tries to escape characters after ` \`.
This is on Windows 10. 

Any suggestions?

**Comment by arthwang** [comment]
Thank you for reporting the non escaping bug that is fixed now.

**Comment by adericotur** [comment]
No problem. And thank your for the fix and the extension!
